sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt install qemu qemu-user-static binfmt-support

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t brucefrankwang/rpi-moinmoin .

deploy:
  skip_cleanup: true
  provider: script
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/$DEPLOY_IMAGE
  on:
    branch: master
