sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt install qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t brucefrankwang/rpi-moinmoin:1.9.9 .
