sudo: required

language: bash

services:
  - docker

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:  
  - docker build -t brucefrankwang/rpi-moinmoin:1.9.9 .
