os: linux
group: stable
dist: trusty

language: bash

sudo: required

services:
  - docker

install:
  - sudo apt install qemu qemu-user-static binfmt-support

script:
  - make build

after_success:
  - echo "Prepare push..."
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make docker_deploy tag=latest