os: linux
group: stable
dist: trusty

language: bash

sudo: required

services:
  - docker

before_install:
  - sudo apt install qemu qemu-user-static binfmt-support

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t brucefrankwang/rpi-moinmoin .

deploy:
  skip_cleanup: true
  provider: script
  script:
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        make docker_deploy tag=latest;
      fi
  on:
    branch: master
